# Form implementation generated from reading ui file 'app/view/Ui_announcementCard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AnnnouncementCard(object):
    def setupUi(self, AnnnouncementCard):
        AnnnouncementCard.setObjectName("AnnnouncementCard")
        AnnnouncementCard.resize(464, 374)
        self.verticalLayout = QtWidgets.QVBoxLayout(AnnnouncementCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.announcementTitleLabel = SubtitleLabel(parent=AnnnouncementCard)
        self.announcementTitleLabel.setObjectName("announcementTitleLabel")
        self.verticalLayout.addWidget(self.announcementTitleLabel)
        self.announcementInfo = QtWidgets.QHBoxLayout()
        self.announcementInfo.setObjectName("announcementInfo")
        self.info_1 = BodyLabel(parent=AnnnouncementCard)
        self.info_1.setObjectName("info_1")
        self.announcementInfo.addWidget(self.info_1)
        self.info_2 = BodyLabel(parent=AnnnouncementCard)
        self.info_2.setObjectName("info_2")
        self.announcementInfo.addWidget(self.info_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.announcementInfo.addItem(spacerItem)
        self.verticalLayout.addLayout(self.announcementInfo)
        self.announcementDetails = QtWidgets.QHBoxLayout()
        self.announcementDetails.setObjectName("announcementDetails")
        self.icon = IconWidget(parent=AnnnouncementCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setObjectName("icon")
        self.announcementDetails.addWidget(self.icon)
        self.detailsLabel = BodyLabel(parent=AnnnouncementCard)
        self.detailsLabel.setObjectName("detailsLabel")
        self.announcementDetails.addWidget(self.detailsLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.announcementDetails.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.announcementDetails)
        self.textBrowser = TextBrowser(parent=AnnnouncementCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(AnnnouncementCard)
        QtCore.QMetaObject.connectSlotsByName(AnnnouncementCard)

    def retranslateUi(self, AnnnouncementCard):
        _translate = QtCore.QCoreApplication.translate
        AnnnouncementCard.setWindowTitle(_translate("AnnnouncementCard", "Form"))
        self.announcementTitleLabel.setText(_translate("AnnnouncementCard", "testAnnouncementTitle"))
        self.info_1.setText(_translate("AnnnouncementCard", "testInfo1"))
        self.info_2.setText(_translate("AnnnouncementCard", "testInfo2"))
        self.detailsLabel.setText(_translate("AnnnouncementCard", "testDetails"))
from qfluentwidgets import BodyLabel, IconWidget, SubtitleLabel, TextBrowser
