# Form implementation generated from reading ui file 'app/view/Ui_course_announcement.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CourseAnnouncementInterface(object):
    def setupUi(self, CourseAnnouncementInterface):
        CourseAnnouncementInterface.setObjectName("CourseAnnouncementInterface")
        CourseAnnouncementInterface.resize(488, 315)
        self.verticalLayout = QtWidgets.QVBoxLayout(CourseAnnouncementInterface)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = SmoothScrollArea(parent=CourseAnnouncementInterface)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setStyleSheet("background-color: transparent;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 295))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PageTitle = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.PageTitle.setObjectName("PageTitle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PageTitle)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.courseTitleLabel = SubtitleLabel(parent=self.PageTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.courseTitleLabel.sizePolicy().hasHeightForWidth())
        self.courseTitleLabel.setSizePolicy(sizePolicy)
        self.courseTitleLabel.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Chinese, QtCore.QLocale.Country.China))
        self.courseTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.courseTitleLabel.setWordWrap(True)
        self.courseTitleLabel.setObjectName("courseTitleLabel")
        self.verticalLayout_2.addWidget(self.courseTitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pageTitleHeader = SubtitleLabel(parent=self.PageTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTitleHeader.sizePolicy().hasHeightForWidth())
        self.pageTitleHeader.setSizePolicy(sizePolicy)
        self.pageTitleHeader.setObjectName("pageTitleHeader")
        self.horizontalLayout.addWidget(self.pageTitleHeader)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.PageTitle)
        self.container = QtWidgets.QVBoxLayout()
        self.container.setObjectName("container")
        self.verticalLayout_3.addLayout(self.container)
        spacerItem1 = QtWidgets.QSpacerItem(20, 198, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(CourseAnnouncementInterface)
        QtCore.QMetaObject.connectSlotsByName(CourseAnnouncementInterface)

    def retranslateUi(self, CourseAnnouncementInterface):
        _translate = QtCore.QCoreApplication.translate
        CourseAnnouncementInterface.setWindowTitle(_translate("CourseAnnouncementInterface", "Form"))
        self.courseTitleLabel.setText(_translate("CourseAnnouncementInterface", "TestCourseTitle"))
        self.pageTitleHeader.setText(_translate("CourseAnnouncementInterface", "TestPageTitleHeader"))
from qfluentwidgets import SmoothScrollArea, SubtitleLabel
