# Form implementation generated from reading ui file 'app/view/Ui_course_teaching_staff_list.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CourseTeachingStaffListInterface(object):
    def setupUi(self, CourseTeachingStaffListInterface):
        CourseTeachingStaffListInterface.setObjectName("CourseTeachingStaffListInterface")
        CourseTeachingStaffListInterface.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(CourseTeachingStaffListInterface)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PageTitle = QtWidgets.QWidget(parent=CourseTeachingStaffListInterface)
        self.PageTitle.setObjectName("PageTitle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PageTitle)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.courseTitleLabel = TitleLabel(parent=self.PageTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.courseTitleLabel.sizePolicy().hasHeightForWidth())
        self.courseTitleLabel.setSizePolicy(sizePolicy)
        self.courseTitleLabel.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Chinese, QtCore.QLocale.Country.China))
        self.courseTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.courseTitleLabel.setObjectName("courseTitleLabel")
        self.verticalLayout_2.addWidget(self.courseTitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pageTitleHeader = TitleLabel(parent=self.PageTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTitleHeader.sizePolicy().hasHeightForWidth())
        self.pageTitleHeader.setSizePolicy(sizePolicy)
        self.pageTitleHeader.setObjectName("pageTitleHeader")
        self.horizontalLayout.addWidget(self.pageTitleHeader)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.PageTitle)
        self.container = QtWidgets.QWidget(parent=CourseTeachingStaffListInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setObjectName("container")
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(CourseTeachingStaffListInterface)
        QtCore.QMetaObject.connectSlotsByName(CourseTeachingStaffListInterface)

    def retranslateUi(self, CourseTeachingStaffListInterface):
        _translate = QtCore.QCoreApplication.translate
        CourseTeachingStaffListInterface.setWindowTitle(_translate("CourseTeachingStaffListInterface", "Form"))
        self.courseTitleLabel.setText(_translate("CourseTeachingStaffListInterface", "TestCourseTitle"))
        self.pageTitleHeader.setText(_translate("CourseTeachingStaffListInterface", "TestPageTitleHeader"))
from qfluentwidgets import TitleLabel
